_G.icons = {
  diagnostic = {
    [vim.diagnostic.severity.ERROR] = "",
    [vim.diagnostic.severity.WARN] = "",
    [vim.diagnostic.severity.INFO] = "",
    [vim.diagnostic.severity.HINT] = "󰌵",
  },
  lspkind = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  symbols = {
    Array = { icon = "", hl = "@constant" },
    Boolean = { icon = "⊨", hl = "@boolean" },
    Class = { icon = "𝓒", hl = "@type" },
    Component = { icon = "󰊕", hl = "@function" },
    Constant = { icon = "", hl = "@constant" },
    Constructor = { icon = "", hl = "@constructor" },
    Enum = { icon = "ℰ", hl = "@type" },
    EnumMember = { icon = "", hl = "@field" },
    Event = { icon = "", hl = "@type" },
    Field = { icon = "", hl = "@field" },
    File = { icon = "", hl = "@text.uri" },
    Fragment = { icon = "", hl = "@constant" },
    Function = { icon = "", hl = "@function" },
    Interface = { icon = "ﰮ", hl = "@type" },
    Key = { icon = "", hl = "@type" },
    Method = { icon = "ƒ", hl = "@method" },
    Module = { icon = "", hl = "@namespace" },
    Namespace = { icon = "", hl = "@namespace" },
    Null = { icon = "NULL", hl = "@type" },
    Number = { icon = "#", hl = "@number" },
    Object = { icon = "⦿", hl = "@type" },
    Operator = { icon = "+", hl = "@operator" },
    Package = { icon = "", hl = "@namespace" },
    Property = { icon = "", hl = "@method" },
    String = { icon = "𝓐", hl = "@string" },
    Struct = { icon = "𝓢", hl = "@type" },
    TypeParameter = { icon = "𝙏", hl = "@parameter" },
    Variable = { icon = "", hl = "@constant" },
  },
  mason_ui = {
    package_installed = "✓",
    package_pending = "➜",
    package_uninstalled = "✗",
  },
  gitsigns = {
    add = { text = "▎" },
    change = { text = "▎" },
    delete = { text = "" },
    topdelete = { text = "" },
    changedelete = { text = "▎" },
    untracked = { text = "▎" },
  },
}
